### ISSUE TITLE
Faulty match of location url

### ISSUE THREAD

**Issue by jatsac** [keydotcat/keycatd#7]
For some cases, the plugin requests to update the password for the wrong location so it would seem it fails to match the urls.
As an example, this is happening when accessing the following URLs:
- https://hpcportal.bsc.es/
- https://www.bsc.es/res-intranet/

Related to this, it may be useful to include the target location name in the banner i.e. replace:
> Do you want to replace the password for this credential?

by:

> Do you want to replace the password for "Location_Name"?

**Comment by acasajus** [comment]
Should be better in version https://github.com/keydotcat/browser/releases/tag/v0.0.16 

Please reopen if it still happens

**Comment by jatsac** [comment]
Location match fails when URL include IPs instead of domain names.
